general:

operation_mode: chain_eqeb

model:
   model_path: ../../stm32ai-modelzoo/re_identification/mobilenetv2/ST_pretrainedmodel_public_dataset/DeepSportradar/mobilenetv2_a035_256_128_fft/mobilenetv2_a035_256_128_fft.keras
dataset: 
   dataset_name: DeepSportradar
   class_names:
   test_query_path:        ./datasets/DeepSportradar-ReID/reid_test/query
   test_gallery_path:      ./datasets/DeepSportradar-ReID/reid_test/gallery
   quantization_path:     ./datasets/DeepSportradar-ReID/reid_training
   quantization_split: 0.2


evaluation:
   reid_distance_metric: cosine  # Optional, choices=['euclidean', 'cosine], default is 'cosine'
   
preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      aspect_ratio: fit
      interpolation: bilinear
   color_mode: rgb

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: int8

tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
   board: STM32N6570-DK #STM32N6570-DK #STM32H747I-DISCO

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}