model:
   model_path: ../../stm32ai-modelzoo/re_identification/osnet/ST_pretrainedmodel_public_dataset/DeepSportradar/osnet_a100_256_128_tfs/osnet_a100_256_128_tfs_int8.tflite

operation_mode: prediction

dataset:
   prediction_query_path:       ./datasets/DeepSportradar-ReID/reid_test/query
   prediction_gallery_path:      ./datasets/DeepSportradar-ReID/reid_test/gallery

prediction:
   reid_distance_metric: 'cosine' # options: 'euclidean', 'cosine'
   target: 'host'

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: nearest
      aspect_ratio: fit
   color_mode: rgb
   

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
