general:
  project_name: human_activity_recognition

operation_mode: deployment

dataset:
  dataset_name: mobility_v1 # mandatory
  class_names: [Stationary,Walking,Jogging,Biking] # optional: if not provided automatically loaded based on the dataset_name
  # [Stationary,Walking,Jogging,Biking] for mobility_v1 [Jogging,Stationary,Stairs,Walking] for wisdm

preprocessing: # Mandatory
  gravity_rot_sup: True # mandatory
  normalization: False # mandatory

model:
  model_path: ../../stm32ai-modelzoo/human_activity_recognition/st_ign/ST_pretrainedmodel_custom_dataset/mobility_v1/st_ign_wl_24/st_ign_wl_24.keras # mandatory

tools:
  stedgeai:
    optimization: balanced
    on_cloud: False
    path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.17.0/STM32CubeIDE/stm32cubeide.exe

deployment:
  c_project_path: ../application_code/sensing/STM32U5/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32U5
    board: B-U585I-IOT02A

mlflow:
  uri: ./tf/src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
