general:
   gpu_memory_limit: 8

model:
   model_type: heatmaps_spe
   model_name: st_movenet_lightning_a100_heatmaps
   input_shape: (192, 192, 3)
   pretrained: True
   final_activation: softmax

operation_mode: chain_tqeb

dataset:
   dataset_name: coco
   keypoints: 17
   training_path: ./datasets/coco_train_single_pose
   test_path: ./datasets/coco_val_single_pose
   quantization_split: 0.01

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb

data_augmentation:
   random_rotation:
      factor: (-0.1,0.1) # -+0.1 = -+36 degree angle
      fill_value: -1.
   random_periodic_resizing:
      image_sizes: [[192,192],[224,224],[256,256]]
   random_contrast:
      factor: 0.4
   random_brightness:
      factor: 0.3
   random_flip:
      mode: horizontal

training:
   resume_training_from: # experiments_outputs/2024_11_06_16_44_31/
   frozen_layers: # (0:154)
   batch_size: 16
   epochs: 1000
   optimizer:
      Adam:
         learning_rate: 0.01
   callbacks:
      ReduceLROnPlateau:
         monitor: val_oks
         mode: max
         factor: 0.25
         min_delta: 0.0001
         patience: 5
      ModelCheckpoint:
         monitor: val_oks
         mode: max
      EarlyStopping:
         monitor: val_oks
         mode: max
         min_delta: 0.0001
         patience: 10
         
quantization:
  quantizer: onnx_quantizer  # onnx_quantizer for ONNX quantization
  quantization_type: PTQ
  quantization_input_type: int8
  quantization_output_type: int8
  granularity: per_channel          # Optional, defaults to "per_channel". 
  onnx_extra_options:
   CalibMovingAverage: True
  export_dir: quantized_models

tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking: # valid options are STM32MP257F-EV1,STM32MP157F-DK2,STM32MP135F-DK
   board: STM32H747I-DISCO

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}