model:
   model_path: ../../stm32ai-modelzoo/pose_estimation/movenet/ST_pretrainedmodel_custom_dataset/custom_coco_person_17kpts/st_movenet_lightning_a100_heatmaps_192/st_movenet_lightning_a100_heatmaps_192.keras
   model_type: heatmaps_spe

operation_mode: chain_qd

dataset:
   dataset_name: coco
   class_names: [person]
   keypoints: 17
   quantization_path: ./datasets/coco_quant_single_pose

preprocessing:
   rescaling: { scale: 1/127.5, offset: -1 }
   resizing:
      aspect_ratio: crop
      interpolation: nearest
   color_mode: rgb

postprocessing:
   kpts_conf_thresh: 0.15

quantization:
  quantizer: TFlite_converter #  TFlite_converter or onnx_quantizer
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
  # optimize: True

tools:
   stedgeai:
      optimization: balanced
      on_cloud: False
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path: ../application_code/pose_estimation/STM32N6/
   IDE: GCC
   verbosity: 1
   hardware_setup:
      serie: STM32N6
      board: STM32N6570-DK 

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}