model:
   model_type: heatmaps_spe
   model_path: ../../stm32ai-modelzoo/pose_estimation/movenet/ST_pretrainedmodel_custom_dataset/custom_coco_person_17kpts/st_movenet_lightning_a100_heatmaps_192/st_movenet_lightning_a100_heatmaps_192.keras

operation_mode: chain_eqeb

dataset:
   dataset_name: coco
   keypoints: 17
   training_path: ./datasets/coco_train_single_pose
   test_path: ./datasets/coco_val_single_pose
   quantization_split: 0.3

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb

quantization:
  quantizer: onnx_quantizer  # onnx_quantizer for ONNX quantization
  quantization_type: PTQ
  quantization_input_type: int8
  quantization_output_type: int8
  granularity: per_channel          # Optional, defaults to "per_channel". 
  onnx_extra_options:
   CalibMovingAverage: True
  export_dir: quantized_models

tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking: # valid options are STM32MP257F-EV1,STM32MP157F-DK2,STM32MP135F-DK
   board: STM32H747I-DISCO

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}