model:
   model_path: ../../stm32ai-modelzoo/pose_estimation/movenet/ST_pretrainedmodel_custom_dataset/custom_coco_person_17kpts/st_movenet_lightning_a100_heatmaps_192/st_movenet_lightning_a100_heatmaps_192_int8.tflite
   model_type: heatmaps_spe  # spe

operation_mode: evaluation

evaluation:
   profile: profile_O3
   input_type: uint8     # int8 / uint8 / float32
   output_type: int8     # int8 / uint8 / float32
   input_chpos: chlast   # chlast / chfirst
   output_chpos: chlast  # chlast / chfirst
   target: stedgeai_n6 # host, stedgeai_host, stedgeai_n6

dataset:
   dataset_name: coco
   keypoints: 17
   test_path: ./datasets/coco_val_single_pose

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

tools:
   stedgeai:
      path_to_stedgeai: C:/ST/STEdgeAI/3.0/Utilities/windows/stedgeai.exe

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}