model:
   model_path: ../../stm32ai-modelzoo/pose_estimation/handlandmarks/Public_pretrainedmodel_custom_dataset/custom_dataset_hands_21kpts/handlandmarks_full_224_int8.tflite
   model_type: hand_spe

operation_mode: prediction

dataset:
   dataset_name: coco
   class_names: [hand]
   keypoints: 21
   prediction_path: ./datasets/coco_test_single_pose

preprocessing:
   rescaling:
      scale: 1/255.
      offset: 0
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

postprocessing:
   kpts_conf_thresh: 0.15

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
