model:
   model_path: ../../stm32ai-modelzoo/pose_estimation/headlandmarks/Public_pretrainedmodel_custom_dataset/custom_dataset_head_468kpts/facelandmarksv1_192_int8.onnx
   model_type: head_spe

operation_mode: prediction

dataset:
   dataset_name: coco
   class_names: [head]
   keypoints: 468
   prediction_path: ./datasets/coco_test_single_pose

preprocessing:
   rescaling:
      scale: 1/255.
      offset: 0
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

postprocessing:
   kpts_conf_thresh: 0.15

mlflow:
  uri: ./tf/src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
