general:
   project_name: COCO_2017_pose_Demo
   logs_dir: logs
   saved_models_dir: saved_models
   gpu_memory_limit: 8
   global_seed: 123

model:
   model_name: st_movenet_lightning_a100_heatmaps  
   model_type: heatmaps_spe
   input_shape: (192, 192, 3)
   pretrained: True
   final_activation: softmax

operation_mode: training

dataset:
   dataset_name: coco
   keypoints: 17
   training_path: ./datasets/coco_train_single_pose
   validation_split: 0.1
   test_path: ./datasets/coco_val_single_pose
   quantization_split: 0.01

preprocessing:
   rescaling: { scale: 1/127.5, offset: -1 }
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb

data_augmentation:
   random_rotation:
      factor: (-0.1,0.1) # -+0.1 = -+36 degree angle
      fill_value: -1.
   random_periodic_resizing:
      image_sizes: [[192,192],[224,224],[256,256]]
   random_contrast:
      factor: 0.4
   random_brightness:
      factor: 0.3
   random_flip:
      mode: horizontal

training:
   resume_training_from: # experiments_outputs/2024_11_06_16_44_31/
   frozen_layers: # (0:154)
   batch_size: 16
   epochs: 1000
   optimizer:
      Adam:
         learning_rate: 0.01
   callbacks:
      ReduceLROnPlateau:
         monitor: val_oks
         mode: max
         factor: 0.25
         min_delta: 0.0001
         patience: 5
      ModelCheckpoint:
         monitor: val_oks
         mode: max
      EarlyStopping:
         monitor: val_oks
         mode: max
         min_delta: 0.0001
         patience: 10

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}