model:
  model_type: deeplab
  model_path: ../../stm32ai-modelzoo/semantic_segmentation/deeplabv3/ST_pretrainedmodel_public_dataset/person_coco_2017_pascal_voc_2012/st_deeplabv3_mnv2_a050_s16_asppv2_320/st_deeplabv3_mnv2_a050_s16_asppv2_320.keras

operation_mode: chain_eqeb

dataset:
  dataset_name: person_coco_2017_pascal_voc_2012
  class_names:
  - background
  - person
  validation_path: ./datasets/COCO2017_VOC2012/JPEGImages
  validation_masks_path: ./datasets/COCO2017_VOC2012/SegmentationClassAug
  validation_files_path: ./datasets/COCO2017_VOC2012/ImageSets/Segmentation/val.txt

  quantization_split: 0.02

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      aspect_ratio: fit
      interpolation: bilinear
   color_mode: rgb

quantization:
  quantizer: onnx_quantizer
  target_opset: 17
  granularity: per_tensor
  quantization_type: PTQ
  quantization_input_type: float 
  quantization_output_type: float
  export_dir: quantized_models
  onnx_extra_options:
    CalibMovingAverage: True
  
tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
   board: STM32MP257F-EV1

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}