model:
  model_type: deeplab
  model_path:  ../../stm32ai-modelzoo/semantic_segmentation/deeplabv3/ST_pretrainedmodel_public_dataset/person_coco_2017_pascal_voc_2012/st_deeplabv3_mnv2_a050_s16_asppv2_320/st_deeplabv3_mnv2_a050_s16_asppv2_320_qdq_int8.onnx

operation_mode: deployment

dataset:
   dataset_name: person_coco_2017_pascal_voc_2012
   class_names: [ "background", "person" ]  #or, classes_file_path
   # classes_file_path : ../../application_code/semantic_segmentation/STM32MP-LINUX/Resources/labelmap.txt
preprocessing:
   resizing:
      interpolation: nearest
      aspect_ratio: fit
   color_mode: rgb

tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path:  ../application_code/semantic_segmentation/STM32MP-LINUX/
   board_deploy_path: /usr/local/semantic-segmentation
   verbosity: 1
   hardware_setup:
      serie: STM32MP2
      board: STM32MP257F-EV1
      ip_address: X.X.X.X

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}