model:
   model_path: # a per tensor quantized FastDepth model
   model_type: fast_depth

operation_mode: benchmarking

preprocessing:
   rescaling:
      scale: 1/225
      offset: 0
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
   board: STM32MP257F-EV1

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}