operation_mode: training

general:
  saved_models_dir: ssdlite_mobilenetv2_pt          
  global_seed: 42

model:
  framework: 'torch' 
  model_type : ssd
  # model_name options for SSD model 
  # ['ssd_mobilenetv1_pt', 'ssdlite_mobilenetv1_pt', 'ssd_mobilenetv2_pt', 'ssdlite_mobilenetv2_pt', 'ssdlite_mobilenetv3small_pt', 'ssdlite_mobilenetv3large_pt']
  model_name: "ssdlite_mobilenetv2_pt"
  width_mult: 1.0
  pretrained: True
  # dataset name coco_person is for pretrained dataset coco_person
  pretrained_dataset : coco_person
  input_shape: [3, 300, 300]
  num_classes: 1

dataset:
  format : coco # coco for 'coco_person' and 'coco'
  dataset_name: coco # coco for 'coco_person' and 'coco'
  num_workers: 8
  training_path : "" # keep empty
  class_names: ["person"] 
  # make sure that only one class is present in this json (person)
  train_images_path : ./datasets/coco/train2017 # image folder (image files)
  train_annotations_path: ./datasets/coco/annotations/instances_train2017_person.json # annotation file json 
  val_images_path : ./datasets/coco/val2017
  val_annotations_path: ./datasets/coco/annotations/instances_val2017_person.json 

training:
  trainer_name : ssd
  batch_size: 32
  epochs: 300
  validation_epochs: 2
  print_interval : 100
  base_net_lr: null             
  extra_layers_lr: null
  momentum: 0.9
  weight_decay: 0.0005
  gamma: 0.1
  scheduler: "cosine"  
  t_max: 200
  optimizer: 
    SGD:
      learning_rate: 0.01 
      momentum: 0.9
      weight_decay: 0.0005

# ---------------- preprocessing Configuration ---------------- #
preprocessing: 
  mean :  [127, 127, 127]
  std : 128.0
  rescaling:
    scale  : 1
    offset : 0 
  resizing:
      aspect_ratio: fit
      interpolation: nearest
  color_mode: rgb

# ---------------- postprocessing Configuration ---------------- #
postprocessing: # 
  confidence_thresh: 0.01
  NMS_thresh: 0.50
  IoU_eval_thresh: 0.5 
  max_detection_boxes: 100

mlflow:
  uri: ./pt/src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./pt/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}