operation_mode: chain_eqe

model:
   model_type: st_yoloxn
   model_path: ../../stm32ai-modelzoo/object_detection/st_yoloxn/ST_pretrainedmodel_public_dataset/coco_2017_person/st_yoloxn_d033_w025_256/st_yoloxn_d033_w025_256.keras
   input_shape: (256,256,3)

dataset:
   dataset_name: coco
   format: tfs
   class_names: [person]
   test_path: /local/data/od_validation_dataset_coco_person/
   quantization_path: /local/data/od_validation_dataset_coco_person/

preprocessing:
   rescaling:
      scale: 1/255
      offset: 0
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb

postprocessing:
   confidence_thresh: 0.001
   NMS_thresh: 0.5
   IoU_eval_thresh: 0.5
   plot_metrics: false
   max_detection_boxes: 100

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float
   export_dir: quantized_models

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}