operation_mode: chain_eqeb

model:
   model_type: st_yololcv1
   model_path: ../../stm32ai-modelzoo/object_detection/st_yololcv1/ST_pretrainedmodel_public_dataset/coco_2017_person/st_yololcv1_192/st_yololcv1_192.keras
   input_shape: (192,192,3)

dataset:
   dataset_name: coco
   format: tfs
   class_names: [person]
   training_path: /local/data/od_validation_dataset_coco_person/
   test_path: /local/data/od_validation_dataset_coco_person/
   quantization_path: /local/data/od_validation_dataset_coco_person/
   validation_path: /local/data/od_validation_dataset_coco_person/
   validation_split: 0.1
   quantization_split: 0.05

preprocessing:
   rescaling:
      scale: 1/255
      offset: 0
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb

postprocessing:
   confidence_thresh: 0.001
   NMS_thresh: 0.5
   IoU_eval_thresh: 0.5
   plot_metrics: #True   # Plot precision versus recall curves. Default is False.
   max_detection_boxes: 100

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float

tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
   board: STM32H747I-DISCO

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}