general:
  project_name: my_project
  saved_models_dir: saved_models
  gpu_memory_limit: 16
  num_threads_tflite: 12
  global_seed: 127

operation_mode: chain_tqe

model: 
  model_type: st_yololcv1
  model_name: st_yololcv1
  input_shape: (192,192,3)

dataset:
  dataset_name: coco
  format: tfs
  class_names: [person]
  training_path: ./datasets/od_coco_2017_person/train
  validation_path: ./datasets/od_coco_2017_person/validation
  test_path: ./datasets/od_coco_2017_person/test
  quantization_path: ./datasets/od_coco_2017_person/quantization
  quantization_split: 0.05

preprocessing:
  rescaling:
    scale: 1/255
    offset: 0
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

data_augmentation:
  random_crop:
    crop_center_x: (0.25, 0.75)
    crop_center_y: (0.25, 0.75)
    crop_width: (0.6, 0.9)
    crop_height: (0.6, 0.9)
    change_rate: 0.5
  random_periodic_resizing:
    period: 20
    image_sizes:
    - (192, 192)
    - (224, 224)
    - (256, 256)
    - (288, 288)
    - (320, 320)
    - (352, 352)
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.3
  random_flip:
    mode: horizontal
  random_rotation:
    factor: 0.02
    fill_mode: wrap
    interpolation: nearest

training:
  dropout: null
  batch_size: 64
  epochs: 500
  optimizer:
    Adam:
      learning_rate: 0.0025
  callbacks:
    LRWarmupCosineDecay:
      initial_lr: 1.0e-05
      warmup_steps: 20
      max_lr: 0.00125
      hold_steps: 20
      decay_steps: 420
      end_lr: 1.0e-06
    EarlyStopping:
      monitor: val_loss
      patience: 100
      restore_best_weights: true
      verbose: 1

postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: false
  max_detection_boxes: 100
      

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float
   export_dir: quantized_models

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
