general:
  project_name: st_yoloxn_d033_w025_256
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: false
  gpu_memory_limit: 16 #24
  num_threads_tflite: 12
  global_seed: 127

operation_mode: chain_tqeb

model: 
  model_type: st_yoloxn
  model_name: st_yoloxn_d033_w025
  input_shape: (256,256,3)

dataset:
  format: coco
  class_names: [person]
  dataset_name: coco
  exclude_unlabeled: true
  download_data: false
  max_detections: 20
  data_dir: ./datasets/COCO_2017_person/tmp/coco_like/
  train_images_path: /local/data/OD_datasets/COCO/train2017
  train_annotations_path: /local/data/OD_datasets/COCO/annotations/person_keypoints_train2017.json
  val_images_path: /local/data/OD_datasets/COCO/val2017
  val_annotations_path: /local/data/OD_datasets/COCO/annotations/person_keypoints_val2017.json
  training_path: ./datasets/COCO_2017_person/tmp/coco_like/train
  validation_split: 0.1
  test_path: ./datasets/COCO_2017_person/tmp/coco_like/test
  quantization_path: /local/data/od_coco_2017_person/train
  quantization_split: 0.001

preprocessing:
  rescaling:
    scale: 1/255
    offset: 0
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

data_augmentation:
  random_crop:
    crop_center_x: (0.25, 0.75)
    crop_center_y: (0.25, 0.75)
    crop_width: (0.6, 0.9)
    crop_height: (0.6, 0.9)
    change_rate: 0.5
  random_periodic_resizing:
    period: 20
    image_sizes:
    - (192, 192)
    - (224, 224)
    - (256, 256)
    - (288, 288)
    - (320, 320)
    - (352, 352)
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.3
  random_flip:
    mode: horizontal
  random_rotation:
    factor: 0.02
    fill_mode: wrap
    interpolation: nearest

training:
  dropout: null
  batch_size: 64
  epochs: 500
  optimizer:
    Adam:
      learning_rate: 0.0025
  callbacks:
    LRWarmupCosineDecay:
      initial_lr: 1.0e-05
      warmup_steps: 20
      max_lr: 0.00125
      hold_steps: 20
      decay_steps: 420
      end_lr: 1.0e-06
    EarlyStopping:
      monitor: val_loss
      patience: 100
      restore_best_weights: true
      verbose: 1

postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: false
  max_detection_boxes: 100

quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

benchmarking:
  board: STM32H747I-DISCO

tools:
   stedgeai:
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe
   
deployment:
  c_project_path: ../application_code/object_detection/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32H7
    board: STM32H747I-DISCO

mlflow:
  uri: ./tf/src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
    
