general:
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: False
  gpu_memory_limit: 24

operation_mode: quantization

model:
  model_type: st_yololcv1
  model_path: ../../stm32ai-modelzoo/object_detection/st_yololcv1/ST_pretrainedmodel_public_dataset/coco_2017_person/st_yololcv1_192/st_yololcv1_192.keras

dataset:
  dataset_name: coco
  format: tfs
  class_names: [person]
  test_path: ./datasets/od_coco_2017_person/test
  quantization_path: ./datasets/od_coco_2017_person/quantization

preprocessing:
  rescaling:
    scale: 1/255
    offset: 0
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

quantization:
  operating_mode: full_auto
  quantizer: Onnx_quantizer
  quantization_type: PTQ
  target_opset: 21
  granularity: per_channel
  export_dir: quantized_models
  quantization_input_type: uint8
  quantization_output_type: float
  onnx_quant_parameters:
    weightType: Int8
    activType: Int8
  onnx_extra_options:
    WeightSymmetric: true
    ActivationSymmetric: false
    QuantizeBias: true
    CalibMovingAverage: true
  iterative_quant_parameters:
    accuracy_tolerance: 1.0

postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: false
  max_detection_boxes: 100

mlflow:
  uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}