model:
   model_path: ../../stm32ai-modelzoo/image_classification/efficientnetv2/ST_pretrainedmodel_public_dataset/food101/efficientnetv2b0_224_fft/efficientnetv2b0_224_fft.keras

operation_mode: chain_qd

dataset:
  dataset_name: food101
  classes_file_path: ./datasets/labels_food101.txt
  quantization_path: ./datasets/food101/quant_set

preprocessing:
  rescaling: { scale: 1/127.5, offset: -1 }
  resizing:
    interpolation: nearest
    aspect_ratio: crop
  color_mode: rgb

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float

tools:
   stedgeai:
      optimization: balanced
      on_cloud: False
      path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path: ../application_code/image_classification/STM32N6/
   IDE: GCC
   verbosity: 1
   hardware_setup:
      serie: STM32N6
      board: STM32N6570-DK #STM32H747I-DISCO, STM32N6570-DK

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}