model:
   model_path: ./optimized_model.onnx #../../stm32ai-modelzoo/image_classification/mobilenetv1/ST_pretrainedmodel_public_dataset/tf_flowers/mobilenetv1_a025_96_grayscale_tfs/mobilenetv1_a025_96_grayscale_tfs.keras

operation_mode: chain_eqe

dataset:
  dataset_name: food101
  class_names:
  - apple_pie
  - baby_back_ribs
  - baklava
  - beef_carpaccio
  - beef_tartare
  - beet_salad
  - beignets
  - bibimbap
  - bread_pudding
  - breakfast_burrito
  - bruschetta
  - caesar_salad
  - cannoli
  - caprese_salad
  - carrot_cake
  - ceviche
  - cheesecake
  - cheese_plate
  - chicken_curry
  - chicken_quesadilla
  - chicken_wings
  - chocolate_cake
  - chocolate_mousse
  - churros
  - clam_chowder
  - club_sandwich
  - crab_cakes
  - creme_brulee
  - croque_madame
  - cup_cakes
  - deviled_eggs
  - donuts
  - dumplings
  - edamame
  - eggs_benedict
  - escargots
  - falafel
  - filet_mignon
  - fish_and_chips
  - foie_gras
  - french_fries
  - french_onion_soup
  - french_toast
  - fried_calamari
  - fried_rice
  - frozen_yogurt
  - garlic_bread
  - gnocchi
  - greek_salad
  - grilled_cheese_sandwich
  - grilled_salmon
  - guacamole
  - gyoza
  - hamburger
  - hot_and_sour_soup
  - hot_dog
  - huevos_rancheros
  - hummus
  - ice_cream
  - lasagna
  - lobster_bisque
  - lobster_roll_sandwich
  - macaroni_and_cheese
  - macarons
  - miso_soup
  - mussels
  - nachos
  - omelette
  - onion_rings
  - oysters
  - pad_thai
  - paella
  - pancakes
  - panna_cotta
  - peking_duck
  - pho
  - pizza
  - pork_chop
  - poutine
  - prime_rib
  - pulled_pork_sandwich
  - ramen
  - ravioli
  - red_velvet_cake
  - risotto
  - samosa
  - sashimi
  - scallops
  - seaweed_salad
  - shrimp_and_grits
  - spaghetti_bolognese
  - spaghetti_carbonara
  - spring_rolls
  - steak
  - strawberry_shortcake
  - sushi
  - tacos
  - takoyaki
  - tiramisu
  - tuna_tartare
  - waffles
  test_path: "/local/datasets/ic_food101/test_nano/"
  quantization_path: "/local/datasets/ic_food101/quant/"

preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb #grayscale

quantization:
  quantizer: Onnx_quantizer
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}