model:
#   model_path: ../../stm32ai-modelzoo/image_classification/mobilenetv2/ST_pretrainedmodel_public_dataset/tf_flowers/mobilenetv2_a035_128_fft/mobilenetv2_a035_128_fft_int8.tflite
   model_path: ../../stm32ai-modelzoo/image_classification/efficientnet/ST_pretrainedmodel_public_dataset/tf_flowers/st_efficientnetlcv1_128_tfs/st_efficientnetlcv1_128_tfs_qdq_int8.onnx
   
operation_mode: prediction

dataset:
   dataset_name: tf_flowers
   class_names: [daisy, dandelion, roses, sunflowers, tulips]
   prediction_path: ./datasets/flowers_predict

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
