general:
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: False
  gpu_memory_limit: 24

model:
   model_path: ../../stm32ai-modelzoo/image_classification/mobilenetv2/ST_pretrainedmodel_public_dataset/tf_flowers/mobilenetv2_a035_224_fft/mobilenetv2_a035_224_fft.keras

operation_mode: quantization

dataset:
  dataset_name: tf_flowers
  test_path: ./datasets/flower_photos_testset
  quantization_path: ./datasets/flower_photos
  quantization_split: 0.01

preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb

quantization:
  operating_mode: full_auto
  quantizer: Onnx_quantizer
  quantization_type: PTQ
  target_opset: 21
  export_dir: quantized_models
  quantization_input_type: uint8
  quantization_output_type: float
  onnx_quant_parameters:
    weightType: Int8
    activType: Int8
  onnx_extra_options:
    WeightSymmetric: true
    ActivationSymmetric: false
    QuantizeBias: true
    CalibMovingAverage: true
  iterative_quant_parameters:
    accuracy_tolerance: 1.5

mlflow:
  uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}