general:
  project_name: coco_instance_seg
  logs_dir: logs
  display_figures: true
  global_seed: 123
  gpu_memory_limit: 4

operation_mode: prediction
model:
  model_type: yolov8n_seg 
  model_path: https://github.com/stm32-hotspot/ultralytics/raw/refs/heads/main/examples/YOLOv8-STEdgeAI/stedgeai_models/segmentation/yolov8n_256_quant_pc_ii_seg_coco-st.tflite

dataset:
  dataset_name: coco_is
  classes_file_path : ./datasets/coco_classes.txt
  class_names: 
  prediction_path: ./datasets/coco/images

preprocessing:
  rescaling:
    scale: 1/255.0
    offset: 0
  resizing:
    interpolation: bilinear
    aspect_ratio: fit
  color_mode: rgb

postprocessing:
  confidence_thresh: 0.5
  IoU_eval_thresh: 0.5
  max_detection_boxes: 10

tools:
  stedgeai:
    optimization: balanced
    on_cloud: true
    path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
  board: STM32MP257F-EV1

deployment:
  c_project_path: 
  IDE: 
  verbosity: 
  hardware_setup:
    serie: 
    board: 
    input: 
    output: 
    label_file_path:

mlflow:
  uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}