general:
  project_name: ReID_model_zoo
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: False
  global_seed: 123
  gpu_memory_limit: 16

model: 
  # model_path: ./tf/src/experiments_outputs/2025_10_31_15_24_06/saved_models/best_model.keras
  model_name: osnet_a025
  # choices: ['efficientnetv2b0', 'efficientnetv2b1', 'efficientnetv2b2', 'efficientnetv2b3', 'efficientnetv2s',
  #           'mobilenetv1_a025', 'mobilenetv1_a050', 'mobilenetv1_a075', 'mobilenetv1_a100',
  #           'mobilenetv2_a035', 'mobilenetv2_a050', 'mobilenetv2_a075', 'mobilenetv2_a100', 'mobilenetv2_a130', 'mobilenetv2_a140',
  #           'resnet50v2', 'resnet8', 'resnet20', 'resnet32', 
  #           'osnet_a025', 'osnet_a050', 'osnet_a075', 'osnet_a100']
  input_shape: (256, 128, 3)
  pretrained:         # Optional, Bool 

operation_mode: training
#choices=['training' , 'evaluation', 'prediction', 'deployment', 'quantization', 'benchmarking',
#        'chain_tqeb','chain_tqe','chain_eqe','chain_qb','chain_eqeb','chain_qd ']

dataset:
  dataset_name: DeepSportradar
  class_names:   # Or, classes_file_path, one of it is mandatory for deployment and prediction.
  training_path: ./datasets/DeepSportradar-ReID/reid_training  # Mandatory
  validation_path:        # Optional
  validation_split: 0.2   # Optional, default value is 0.2
  test_query_path:        ./datasets/DeepSportradar-ReID/reid_test/query
  test_gallery_path:      ./datasets/DeepSportradar-ReID/reid_test/gallery
  prediction_query_path:       ./datasets/DeepSportradar-ReID/reid_test/query
  prediction_gallery_path: ./datasets/DeepSportradar-ReID/reid_test/gallery
  quantization_path:      # Optional
  quantization_split:     0.1  # Optional, default value is 0.05
  check_image_files: False  # Optional, set it to True if you want to check that all the image files can be read successfully
  seed: 127               # Optional, there is a default seed

preprocessing:
  rescaling: { scale: 1/127.5, offset: -1 }
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb

data_augmentation:    # Optional section
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.05
  random_flip:
    mode: horizontal
  random_translation:
    width_factor: 0.25
    height_factor: 0.25
    fill_mode: reflect
    interpolation: nearest
  random_rotation:
    factor: 0.125
    fill_mode: reflect
    interpolation: nearest
  random_zoom:
    width_factor: 0.25
    height_factor: 0.25
    fill_mode: reflect
    interpolation: nearest
  random_shear:
    factor: 0.0515
    fill_mode: wrap
    interpolation: nearest
  random_rectangle_erasing:
    'nrec': (0, 3)
  # random_gaussian_noise:
  #   stddev: (0.0001, 0.005)
  

training:
  resume_training_from: # Optional, use to resume a training from a previous experiment.
                        # Example: experiments_outputs/2023_10_26_18_36_09/saved_models/last_augmented_model.h5 
  frozen_layers: None  #(0:-1)            # Optional, use if you want to freeze some layers (by default all layers are trainable)
  dropout:  0.3                     # Optional, use it if you want a dropout layer to be included in the model
  batch_size: 128
  epochs: 2
  optimizer:
    Adam:
      learning_rate: 0.01
  callbacks:          # Optional section
    ReduceLROnPlateau:
      monitor: val_loss
      mode: min
      factor: 0.7
      patience: 40
      min_lr: 1.0e-05
    # LRWarmupCosineDecay:
    #   initial_lr: 0.0001
    #   warmup_steps: 100
    #   max_lr: 0.01
    #   hold_steps: 100
    #   decay_steps: 800
    #   end_lr: 5.0e-05
    EarlyStopping:
      monitor: val_loss
      mode: min
      restore_best_weights: true
      patience: 100
  triplet_loss:
    margin: 0.3  # Optional between [0, 1], default is 0.3
    strategy: hard   #choices=['hard', 'semi_hard', 'simple'], default is 'hard'  
    distance_metric: cosine  # Optional, choices=['euclidean', 'cosine'], default is 'cosine'
#  trained_model_path: trained.h5   # Optional, use it if you want to save the best model at the end of the training to a path of your choice

quantization:
  quantizer: Onnx_quantizer #choices=['TFlite_converter', 'Onnx_quantizer']
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: uint8
  granularity: per_channel   #per_tensor
  optimize: False   #can be True if per_tensor
  export_dir: quantized_models

evaluation:
  reid_distance_metric: euclidean  #choices=['euclidean', 'cosine'], default is 'cosine'

# The prediction section is optional unless you set operation_mode to "prediction".
# If you do so, the attribute test_files_path and test_gallery_files_path are mandatory.
prediction:
  target: 'host'
  reid_distance_metric: cosine  #choices=['euclidean', 'cosine'], default is 'cosine'
  # test_files_path: ./datasets/DeepSportradar-ReID/reid_test/query
  # test_gallery_files_path: ./datasets/DeepSportradar-ReID/reid_test/gallery

tools:
  stedgeai:
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/ST/STEdgeAI/<x.y>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
  board: STM32N6570-DKq 
  # choice: ['STM32MP157F-DK2', 'STM32MP257F-EV1', 'STM32MP135F-DK', 'STM32F469I-DISCO', 'ISM330IS', 'LSM6DSO16IS', 'STM32L4R9I-DISCO', 'STM32N6570-DK', 'STM32H573I-DK', 'STM32H7B3I-DK', 'STM32H7S78-DK', 'NUCLEO-F401RE', 'NUCLEO-G474RE', 'B-U585I-IOT02A', 'NUCLEO-H743ZI2', 'STM32F769I-DISCO', 'STM32H735G-DK', 'STM32H747I-DISCO', 'STM32F746G-DISCO', 'SR5E1-EVBE3000D', 'SR6PX-EVBC4000P']

deployment:
  c_project_path: 
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32H7
    board: STM32H747I-DISCO

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
