operation_mode: chain_eqe

general:
  workers: 4 
  no_prefetcher: true
  display_figures: False 

model: 
  framework: 'torch' # Must have
  model_name: 'mobilenetv2_w035_pt' 
  # model_path: with .pt file we require model_name as well
  pretrained: True
  pretrained_dataset: "imagenet"
  input_shape: [3, 224, 224]

quantization:
   quantizer: Onnx_quantizer
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float
   export_dir: quantized_models

dataset:
  dataset_name: "imagenet" # options "flowers102", "food101", "imagenet"
  class_names: ''
  classes_file_path: ./datasets/deployment_labels_imagenet.txt
  data_dir: "/local/datasets/" # there shud be imagenet folder inside this directory # can also be used for quantization
  num_classes: 1000 # change according to your dataset
  train_split: "train"
  val_split: "validation"
  quantization_split: 0.01
  # test_path: you can provide path to test data and it will be used for validation
  # quantization_path: this will be used for quantization otherwise training data will be used

preprocessing: 
  rescaling:
    scale: 1/255.0
    offset: 0
  resizing:
    interpolation: nearest # nearest 'Image resize interpolation type (overrides model)'
    aspect_ratio: fit
  color_mode: rgb

mlflow:
  uri: ./pt/src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./pt/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}